sonar.projectKey=krayin-laravel-crm-devsecops
sonar.projectName=Krayin Laravel CRM DevSecOps
sonar.projectVersion=1.0

sonar.sources=app,config,database,packages,resources,routes
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**,coverage/**,output/**,.phpunit.cache/**
sonar.test.exclusions=vendor/**,node_modules/**

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.tests.reportPath=reports/tests/junit.xml

